# # Derived distribution from input-dir
# target_pairs={2: 11, 3: 8, 4: 7, 5: 4}
# high_sum_bins={2: [(10, (1.0, 2.0))], 3: [(3, (1.0, 2.0)), (5, (2.0, 3.0))], 5: [(1, (1.0, 2.0)), (2, (2.0, 3.0)), (1, (3.0, 4.0))], 4: [(2, (1.0, 2.0)), (4, (2.0, 3.0)), (1, (3.0, 4.0))]}
# by_k={'2': 11, '3': 8, '4': 7, '5': 4}
# by_bin={'k2:(1.00,2.00]': 10, 'k2:<=1.0': 1, 'k3:(1.00,2.00]': 3, 'k3:(2.00,3.00]': 5, 'k4:(1.00,2.00]': 2, 'k4:(2.00,3.00]': 4, 'k4:(3.00,4.00]': 1, 'k5:(1.00,2.00]': 1, 'k5:(2.00,3.00]': 2, 'k5:(3.00,4.00]': 1}
# Wrote ./01_study/inputs/P01_S1_T01_bo_top.yml | prompt: A drawing of a house
# Wrote ./01_study/inputs/P01_S1_T02_gallery.yml | prompt: A drawing of an airplane
# Wrote ./01_study/inputs/P01_S1_T03_slider.yml | prompt: A drawing of a bird
# Wrote ./01_study/inputs/P01_S2_T01_gallery.yml | prompt: A drawing of a cat
# Wrote ./01_study/inputs/P01_S2_T02_slider.yml | prompt: A portrait of a man
# Wrote ./01_study/inputs/P01_S2_T03_bo_top.yml | prompt: A drawing of a shark
# Wrote ./01_study/inputs/P02_S1_T01_gallery.yml | prompt: A drawing of a horse
# Wrote ./01_study/inputs/P02_S1_T02_slider.yml | prompt: A drawing of a lamp
# Wrote ./01_study/inputs/P02_S1_T03_bo_top.yml | prompt: A drawing of a rose
# Wrote ./01_study/inputs/P02_S2_T01_slider.yml | prompt: A drawing of a mountain
# Wrote ./01_study/inputs/P02_S2_T02_bo_top.yml | prompt: A drawing of a ship
# Wrote ./01_study/inputs/P02_S2_T03_gallery.yml | prompt: A drawing of an apple
# Wrote ./01_study/inputs/P03_S1_T01_slider.yml | prompt: A drawing of a horse
# Wrote ./01_study/inputs/P03_S1_T02_bo_top.yml | prompt: A drawing of a bird
# Wrote ./01_study/inputs/P03_S1_T03_gallery.yml | prompt: A drawing of a rose
# Wrote ./01_study/inputs/P03_S2_T01_bo_top.yml | prompt: A portrait of a man
# Wrote ./01_study/inputs/P03_S2_T02_slider.yml | prompt: A drawing of an apple
# Wrote ./01_study/inputs/P03_S2_T03_gallery.yml | prompt: A drawing of a ship
# Wrote ./01_study/inputs/P04_S1_T01_bo_top.yml | prompt: A drawing of a lamp
# Wrote ./01_study/inputs/P04_S1_T02_slider.yml | prompt: A drawing of an airplane
# Wrote ./01_study/inputs/P04_S1_T03_gallery.yml | prompt: A drawing of a house
# Wrote ./01_study/inputs/P04_S2_T01_slider.yml | prompt: A drawing of a cat
# Wrote ./01_study/inputs/P04_S2_T02_gallery.yml | prompt: A drawing of a shark
# Wrote ./01_study/inputs/P04_S2_T03_bo_top.yml | prompt: A drawing of a mountain
# Wrote ./01_study/inputs/P05_S1_T01_slider.yml | prompt: A drawing of a house
# Wrote ./01_study/inputs/P05_S1_T02_gallery.yml | prompt: A drawing of a lamp
# Wrote ./01_study/inputs/P05_S1_T03_bo_top.yml | prompt: A drawing of a horse
# Wrote ./01_study/inputs/P05_S2_T01_gallery.yml | prompt: A drawing of a mountain
# Wrote ./01_study/inputs/P05_S2_T02_bo_top.yml | prompt: A drawing of an apple
# Wrote ./01_study/inputs/P05_S2_T03_slider.yml | prompt: A drawing of a shark
# Wrote ./01_study/inputs/P06_S1_T01_gallery.yml | prompt: A drawing of a bird
# Wrote ./01_study/inputs/P06_S1_T02_bo_top.yml | prompt: A drawing of an airplane
# Wrote ./01_study/inputs/P06_S1_T03_slider.yml | prompt: A drawing of a rose
# Wrote ./01_study/inputs/P06_S2_T01_bo_top.yml | prompt: A drawing of a cat
# Wrote ./01_study/inputs/P06_S2_T02_gallery.yml | prompt: A portrait of a man
# Wrote ./01_study/inputs/P06_S2_T03_slider.yml | prompt: A drawing of a ship
# Wrote ./01_study/inputs/P07_S1_T01_bo_top.yml | prompt: A drawing of an oak
# Wrote ./01_study/inputs/P07_S1_T02_gallery.yml | prompt: A portrait of a girl
# Wrote ./01_study/inputs/P07_S1_T03_slider.yml | prompt: A portrait of a baby
# Wrote ./01_study/inputs/P07_S2_T01_gallery.yml | prompt: A drawing of a chair
# Wrote ./01_study/inputs/P07_S2_T02_slider.yml | prompt: A drawing of a truck
# Wrote ./01_study/inputs/P07_S2_T03_bo_top.yml | prompt: A drawing of an elephant
# Wrote ./01_study/inputs/P08_S1_T01_gallery.yml | prompt: A drawing of a train
# Wrote ./01_study/inputs/P08_S1_T02_slider.yml | prompt: A drawing of a dog
# Wrote ./01_study/inputs/P08_S1_T03_bo_top.yml | prompt: A drawing of a tiger
# Wrote ./01_study/inputs/P08_S2_T01_slider.yml | prompt: A portrait of a woman
# Wrote ./01_study/inputs/P08_S2_T02_bo_top.yml | prompt: A drawing of a frog
# Wrote ./01_study/inputs/P08_S2_T03_gallery.yml | prompt: A drawing of a deer
# Wrote ./01_study/inputs/P09_S1_T01_slider.yml | prompt: A drawing of a train
# Wrote ./01_study/inputs/P09_S1_T02_bo_top.yml | prompt: A portrait of a baby
# Wrote ./01_study/inputs/P09_S1_T03_gallery.yml | prompt: A drawing of a tiger
# Wrote ./01_study/inputs/P09_S2_T01_bo_top.yml | prompt: A drawing of a truck
# Wrote ./01_study/inputs/P09_S2_T02_slider.yml | prompt: A drawing of a deer
# Wrote ./01_study/inputs/P09_S2_T03_gallery.yml | prompt: A drawing of a frog
# Wrote ./01_study/inputs/P10_S1_T01_bo_top.yml | prompt: A drawing of a dog
# Wrote ./01_study/inputs/P10_S1_T02_slider.yml | prompt: A portrait of a girl
# Wrote ./01_study/inputs/P10_S1_T03_gallery.yml | prompt: A drawing of an oak
# Wrote ./01_study/inputs/P10_S2_T01_slider.yml | prompt: A drawing of a chair
# Wrote ./01_study/inputs/P10_S2_T02_gallery.yml | prompt: A drawing of an elephant
# Wrote ./01_study/inputs/P10_S2_T03_bo_top.yml | prompt: A portrait of a woman
# Wrote ./01_study/inputs/P11_S1_T01_slider.yml | prompt: A drawing of an oak
# Wrote ./01_study/inputs/P11_S1_T02_gallery.yml | prompt: A drawing of a dog
# Wrote ./01_study/inputs/P11_S1_T03_bo_top.yml | prompt: A drawing of a train
# Wrote ./01_study/inputs/P11_S2_T01_gallery.yml | prompt: A portrait of a woman
# Wrote ./01_study/inputs/P11_S2_T02_bo_top.yml | prompt: A drawing of a deer
# Wrote ./01_study/inputs/P11_S2_T03_slider.yml | prompt: A drawing of an elephant
# Wrote ./01_study/inputs/P12_S1_T01_gallery.yml | prompt: A portrait of a baby
# Wrote ./01_study/inputs/P12_S1_T02_bo_top.yml | prompt: A portrait of a girl
# Wrote ./01_study/inputs/P12_S1_T03_slider.yml | prompt: A drawing of a tiger
# Wrote ./01_study/inputs/P12_S2_T01_bo_top.yml | prompt: A drawing of a chair
# Wrote ./01_study/inputs/P12_S2_T02_gallery.yml | prompt: A drawing of a truck
# Wrote ./01_study/inputs/P12_S2_T03_slider.yml | prompt: A drawing of a frog
# Done. Wrote 72 config files for 12 participants to: ./01_study/inputs

# # Session sample distributions
# Session 1 (main): desired={(2, '(1.00,2.00]'): 2, (3, '(1.00,2.00]'): 1, (3, '(2.00,3.00]'): 1, (4, '(2.00,3.00]'): 1, (5, '(2.00,3.00]'): 1}, actual=defaultdict(<class 'int'>, {(2, '(1.00,2.00]'): 2, (3, '(1.00,2.00]'): 1, (2, '<=1.0'): 0, (5, '(3.00,4.00]'): 0, (4, '(3.00,4.00]'): 0, (5, '(2.00,3.00]'): 1, (4, '(2.00,3.00]'): 1, (4, '(1.00,2.00]'): 0, (3, '(2.00,3.00]'): 1}), by_k={'2': 2, '3': 2, '4': 1, '5': 1}, by_bin={'k2:(1.00,2.00]': 2, 'k3:(1.00,2.00]': 1, 'k3:(2.00,3.00]': 1, 'k4:(2.00,3.00]': 1, 'k5:(2.00,3.00]': 1}
# Session 1 (no k5): desired={(2, '(1.00,2.00]'): 3, (3, '(1.00,2.00]'): 1, (3, '(2.00,3.00]'): 1, (4, '(2.00,3.00]'): 1}, actual=defaultdict(<class 'int'>, {(2, '(1.00,2.00]'): 3, (2, '<=1.0'): 0, (4, '(3.00,4.00]'): 0, (3, '(1.00,2.00]'): 1, (4, '(2.00,3.00]'): 1, (4, '(1.00,2.00]'): 0, (3, '(2.00,3.00]'): 1}), by_k={'2': 3, '3': 2, '4': 1}, by_bin={'k2:(1.00,2.00]': 3, 'k3:(1.00,2.00]': 1, 'k3:(2.00,3.00]': 1, 'k4:(2.00,3.00]': 1}
# Session 2 (main): desired={(2, '(1.00,2.00]'): 2, (3, '(1.00,2.00]'): 1, (3, '(2.00,3.00]'): 1, (4, '(2.00,3.00]'): 1, (5, '(2.00,3.00]'): 1}, actual=defaultdict(<class 'int'>, {(2, '<=1.0'): 0, (5, '(3.00,4.00]'): 0, (4, '(3.00,4.00]'): 0, (2, '(1.00,2.00]'): 2, (4, '(2.00,3.00]'): 1, (4, '(1.00,2.00]'): 0, (3, '(2.00,3.00]'): 1, (3, '(1.00,2.00]'): 1, (5, '(2.00,3.00]'): 1}), by_k={'2': 2, '3': 2, '4': 1, '5': 1}, by_bin={'k2:(1.00,2.00]': 2, 'k3:(1.00,2.00]': 1, 'k3:(2.00,3.00]': 1, 'k4:(2.00,3.00]': 1, 'k5:(2.00,3.00]': 1}
# Session 2 (no k5): desired={(2, '(1.00,2.00]'): 3, (3, '(1.00,2.00]'): 1, (3, '(2.00,3.00]'): 1, (4, '(2.00,3.00]'): 1}, actual=defaultdict(<class 'int'>, {(2, '<=1.0'): 1, (4, '(3.00,4.00]'): 0, (4, '(1.00,2.00]'): 0, (4, '(2.00,3.00]'): 1, (3, '(2.00,3.00]'): 1, (2, '(1.00,2.00]'): 3}), by_k={'2': 4, '3': 1, '4': 1}, by_bin={'k2:(1.00,2.00]': 3, 'k2:<=1.0': 1, 'k3:(2.00,3.00]': 1, 'k4:(2.00,3.00]': 1}

# # Final assignments (prompt per participant/session/interface)
# P01 (GA) S1: bo_top: k5 (2.00,3.00] 'A drawing of a house' | gallery: k3 (1.00,2.00] 'A drawing of an airplane' | slider: k2 (1.00,2.00] 'A drawing of a bird'
# P02 (GA) S1: bo_top: k2 (1.00,2.00] 'A drawing of a rose' | gallery: k3 (2.00,3.00] 'A drawing of a horse' | slider: k4 (2.00,3.00] 'A drawing of a lamp'
# P03 (GA) S1: bo_top: k2 (1.00,2.00] 'A drawing of a bird' | gallery: k2 (1.00,2.00] 'A drawing of a rose' | slider: k3 (2.00,3.00] 'A drawing of a horse'
# P04 (GA) S1: bo_top: k4 (2.00,3.00] 'A drawing of a lamp' | gallery: k5 (2.00,3.00] 'A drawing of a house' | slider: k3 (1.00,2.00] 'A drawing of an airplane'
# P05 (GA) S1: bo_top: k3 (2.00,3.00] 'A drawing of a horse' | gallery: k4 (2.00,3.00] 'A drawing of a lamp' | slider: k5 (2.00,3.00] 'A drawing of a house'
# P06 (GA) S1: bo_top: k3 (1.00,2.00] 'A drawing of an airplane' | gallery: k2 (1.00,2.00] 'A drawing of a bird' | slider: k2 (1.00,2.00] 'A drawing of a rose'
# P07 (GB) S1: bo_top: k2 (1.00,2.00] 'A drawing of an oak' | gallery: k3 (1.00,2.00] 'A portrait of a girl' | slider: k2 (1.00,2.00] 'A portrait of a baby'
# P08 (GB) S1: bo_top: k2 (1.00,2.00] 'A drawing of a tiger' | gallery: k3 (2.00,3.00] 'A drawing of a train' | slider: k4 (2.00,3.00] 'A drawing of a dog'
# P09 (GB) S1: bo_top: k2 (1.00,2.00] 'A portrait of a baby' | gallery: k2 (1.00,2.00] 'A drawing of a tiger' | slider: k3 (2.00,3.00] 'A drawing of a train'
# P10 (GB) S1: bo_top: k4 (2.00,3.00] 'A drawing of a dog' | gallery: k2 (1.00,2.00] 'A drawing of an oak' | slider: k3 (1.00,2.00] 'A portrait of a girl'
# P11 (GB) S1: bo_top: k3 (2.00,3.00] 'A drawing of a train' | gallery: k4 (2.00,3.00] 'A drawing of a dog' | slider: k2 (1.00,2.00] 'A drawing of an oak'
# P12 (GB) S1: bo_top: k3 (1.00,2.00] 'A portrait of a girl' | gallery: k2 (1.00,2.00] 'A portrait of a baby' | slider: k2 (1.00,2.00] 'A drawing of a tiger'
# P01 (GA) S2: bo_top: k2 (1.00,2.00] 'A drawing of a shark' | gallery: k5 (2.00,3.00] 'A drawing of a cat' | slider: k2 (1.00,2.00] 'A portrait of a man'
# P02 (GA) S2: bo_top: k3 (1.00,2.00] 'A drawing of a ship' | gallery: k3 (2.00,3.00] 'A drawing of an apple' | slider: k4 (2.00,3.00] 'A drawing of a mountain'
# P03 (GA) S2: bo_top: k2 (1.00,2.00] 'A portrait of a man' | gallery: k3 (1.00,2.00] 'A drawing of a ship' | slider: k3 (2.00,3.00] 'A drawing of an apple'
# P04 (GA) S2: bo_top: k4 (2.00,3.00] 'A drawing of a mountain' | gallery: k2 (1.00,2.00] 'A drawing of a shark' | slider: k5 (2.00,3.00] 'A drawing of a cat'
# P05 (GA) S2: bo_top: k3 (2.00,3.00] 'A drawing of an apple' | gallery: k4 (2.00,3.00] 'A drawing of a mountain' | slider: k2 (1.00,2.00] 'A drawing of a shark'
# P06 (GA) S2: bo_top: k5 (2.00,3.00] 'A drawing of a cat' | gallery: k2 (1.00,2.00] 'A portrait of a man' | slider: k3 (1.00,2.00] 'A drawing of a ship'
# P07 (GB) S2: bo_top: k2 <=1.0 'A drawing of an elephant' | gallery: k2 (1.00,2.00] 'A drawing of a chair' | slider: k2 (1.00,2.00] 'A drawing of a truck'
# P08 (GB) S2: bo_top: k2 (1.00,2.00] 'A drawing of a frog' | gallery: k3 (2.00,3.00] 'A drawing of a deer' | slider: k4 (2.00,3.00] 'A portrait of a woman'
# P09 (GB) S2: bo_top: k2 (1.00,2.00] 'A drawing of a truck' | gallery: k2 (1.00,2.00] 'A drawing of a frog' | slider: k3 (2.00,3.00] 'A drawing of a deer'
# P10 (GB) S2: bo_top: k4 (2.00,3.00] 'A portrait of a woman' | gallery: k2 <=1.0 'A drawing of an elephant' | slider: k2 (1.00,2.00] 'A drawing of a chair'
# P11 (GB) S2: bo_top: k3 (2.00,3.00] 'A drawing of a deer' | gallery: k4 (2.00,3.00] 'A portrait of a woman' | slider: k2 <=1.0 'A drawing of an elephant'
# P12 (GB) S2: bo_top: k2 (1.00,2.00] 'A drawing of a chair' | gallery: k2 (1.00,2.00] 'A drawing of a truck' | slider: k2 (1.00,2.00] 'A drawing of a frog'

# # Interface order (balanced Latin square)
# P01 session 1: bo_top, gallery, slider
# P01 session 2: gallery, slider, bo_top
# P02 session 1: gallery, slider, bo_top
# P02 session 2: slider, bo_top, gallery
# P03 session 1: slider, bo_top, gallery
# P03 session 2: bo_top, slider, gallery
# P04 session 1: bo_top, slider, gallery
# P04 session 2: slider, gallery, bo_top
# P05 session 1: slider, gallery, bo_top
# P05 session 2: gallery, bo_top, slider
# P06 session 1: gallery, bo_top, slider
# P06 session 2: bo_top, gallery, slider
# P07 session 1: bo_top, gallery, slider
# P07 session 2: gallery, slider, bo_top
# P08 session 1: gallery, slider, bo_top
# P08 session 2: slider, bo_top, gallery
# P09 session 1: slider, bo_top, gallery
# P09 session 2: bo_top, slider, gallery
# P10 session 1: bo_top, slider, gallery
# P10 session 2: slider, gallery, bo_top
# P11 session 1: slider, gallery, bo_top
# P11 session 2: gallery, bo_top, slider
# P12 session 1: gallery, bo_top, slider
# P12 session 2: bo_top, gallery, slider

# Demographic commands
PORT=8000; PID=P01; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P01_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8001; PID=P02; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P02_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8002; PID=P03; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P03_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8003; PID=P04; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P04_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8004; PID=P05; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P05_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8005; PID=P06; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P06_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8006; PID=P07; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P07_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8007; PID=P08; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P08_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8008; PID=P09; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P09_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8009; PID=P10; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P10_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8010; PID=P11; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P11_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1
PORT=8011; PID=P12; python ./server_slider.py --port ${PORT} --demographic ${PID} --config ./01_study/tutorial_inputs/P12_tut_S1_T01_slider.yml --ssh >server_${PID}.log 2>&1

# Tutorial session run commands
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01_tut/P01_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P01_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P01_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01_tut/P01_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P01_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P01_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01_tut/P01_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P01_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P01_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02_tut/P02_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P02_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P02_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02_tut/P02_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P02_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P02_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02_tut/P02_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P02_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P02_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03_tut/P03_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P03_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P03_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03_tut/P03_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P03_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P03_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03_tut/P03_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P03_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P03_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04_tut/P04_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P04_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P04_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04_tut/P04_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P04_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P04_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04_tut/P04_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P04_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P04_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05_tut/P05_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P05_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P05_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05_tut/P05_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P05_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P05_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05_tut/P05_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P05_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P05_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06_tut/P06_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P06_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P06_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06_tut/P06_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P06_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P06_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06_tut/P06_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P06_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P06_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07_tut/P07_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P07_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P07_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07_tut/P07_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P07_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P07_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07_tut/P07_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P07_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P07_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08_tut/P08_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P08_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P08_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08_tut/P08_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P08_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P08_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08_tut/P08_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P08_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P08_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09_tut/P09_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P09_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P09_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09_tut/P09_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P09_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P09_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09_tut/P09_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P09_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P09_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10_tut/P10_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P10_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P10_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10_tut/P10_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P10_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P10_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10_tut/P10_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P10_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P10_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11_tut/P11_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P11_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P11_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11_tut/P11_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P11_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P11_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11_tut/P11_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P11_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P11_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12_tut/P12_tut_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P12_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P12_tut_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12_tut/P12_tut_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P12_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P12_tut_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12_tut/P12_tut_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P12_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/tutorial_inputs/P12_tut_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1

# Session run commands
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S1_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P01_S1_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S1_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S1_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P01_S1_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S1_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S1_slider_T03"; LOG_PATH="${LOG_DIR}/server_P01_S1_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S1_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S2_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P01_S2_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S2_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S2_slider_T02"; LOG_PATH="${LOG_DIR}/server_P01_S2_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S2_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8000; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P01/P01_S2_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P01_S2_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P01_S2_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S1_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P02_S1_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S1_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S1_slider_T02"; LOG_PATH="${LOG_DIR}/server_P02_S1_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S1_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S1_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P02_S1_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S1_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S2_slider_T01"; LOG_PATH="${LOG_DIR}/server_P02_S2_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S2_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S2_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P02_S2_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S2_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8001; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P02/P02_S2_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P02_S2_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P02_S2_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P03_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P03_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P03_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S2_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P03_S2_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S2_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S2_slider_T02"; LOG_PATH="${LOG_DIR}/server_P03_S2_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S2_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8002; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P03/P03_S2_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P03_S2_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P03_S2_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S1_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P04_S1_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S1_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S1_slider_T02"; LOG_PATH="${LOG_DIR}/server_P04_S1_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S1_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P04_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S2_slider_T01"; LOG_PATH="${LOG_DIR}/server_P04_S2_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S2_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S2_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P04_S2_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S2_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8003; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P04/P04_S2_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P04_S2_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P04_S2_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P05_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S1_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P05_S1_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S1_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S1_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P05_S1_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S1_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S2_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P05_S2_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S2_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S2_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P05_S2_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S2_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8004; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P05/P05_S2_slider_T03"; LOG_PATH="${LOG_DIR}/server_P05_S2_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P05_S2_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S1_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P06_S1_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S1_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P06_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S1_slider_T03"; LOG_PATH="${LOG_DIR}/server_P06_S1_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S1_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S2_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P06_S2_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S2_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S2_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P06_S2_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S2_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8005; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P06/P06_S2_slider_T03"; LOG_PATH="${LOG_DIR}/server_P06_S2_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P06_S2_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S1_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P07_S1_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S1_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S1_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P07_S1_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S1_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S1_slider_T03"; LOG_PATH="${LOG_DIR}/server_P07_S1_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S1_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S2_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P07_S2_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S2_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S2_slider_T02"; LOG_PATH="${LOG_DIR}/server_P07_S2_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S2_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8006; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P07/P07_S2_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P07_S2_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P07_S2_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S1_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P08_S1_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S1_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S1_slider_T02"; LOG_PATH="${LOG_DIR}/server_P08_S1_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S1_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S1_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P08_S1_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S1_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S2_slider_T01"; LOG_PATH="${LOG_DIR}/server_P08_S2_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S2_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S2_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P08_S2_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S2_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8007; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P08/P08_S2_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P08_S2_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P08_S2_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P09_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P09_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P09_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S2_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P09_S2_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S2_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S2_slider_T02"; LOG_PATH="${LOG_DIR}/server_P09_S2_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S2_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8008; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P09/P09_S2_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P09_S2_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P09_S2_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S1_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P10_S1_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S1_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S1_slider_T02"; LOG_PATH="${LOG_DIR}/server_P10_S1_slider_T02.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S1_T02_slider.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S1_gallery_T03"; LOG_PATH="${LOG_DIR}/server_P10_S1_gallery_T03.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S1_T03_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S2_slider_T01"; LOG_PATH="${LOG_DIR}/server_P10_S2_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S2_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S2_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P10_S2_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S2_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8009; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P10/P10_S2_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P10_S2_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P10_S2_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S1_slider_T01"; LOG_PATH="${LOG_DIR}/server_P11_S1_slider_T01.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S1_T01_slider.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S1_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P11_S1_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S1_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S1_bo_top_T03"; LOG_PATH="${LOG_DIR}/server_P11_S1_bo_top_T03.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S1_T03_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S2_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P11_S2_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S2_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S2_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P11_S2_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S2_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8010; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P11/P11_S2_slider_T03"; LOG_PATH="${LOG_DIR}/server_P11_S2_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P11_S2_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S1_gallery_T01"; LOG_PATH="${LOG_DIR}/server_P12_S1_gallery_T01.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S1_T01_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S1_bo_top_T02"; LOG_PATH="${LOG_DIR}/server_P12_S1_bo_top_T02.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S1_T02_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S1_slider_T03"; LOG_PATH="${LOG_DIR}/server_P12_S1_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S1_T03_slider.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S2_bo_top_T01"; LOG_PATH="${LOG_DIR}/server_P12_S2_bo_top_T01.log"; python "./server_bo_top.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S2_T01_bo_top.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S2_gallery_T02"; LOG_PATH="${LOG_DIR}/server_P12_S2_gallery_T02.log"; python "./server_gallery.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S2_T02_gallery.yml >"${LOG_PATH}" 2>&1
PORT=8011; STATE_DIR=/nfs/artemis.dgpsrv/ondemand29/chenxil/code/interactive-ranking/01_study; LOG_DIR=./01_study/logs/; STATE_PATH="${STATE_DIR}/P12/P12_S2_slider_T03"; LOG_PATH="${LOG_DIR}/server_P12_S2_slider_T03.log"; python "./server_slider.py" --port "${PORT}" --save-state-dir "${STATE_PATH}" --ssh --config ./01_study/inputs/P12_S2_T03_slider.yml >"${LOG_PATH}" 2>&1
